### ISSUE TITLE
Some questions about vault-token and api-gateway

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-compose#119]
It's me again. I am having some problems configuring the secret store and API gateway.
1. **There is no `edgexfoundryCA.pem` in `/vault/config/pki/`**. I looked at the [document](https://docs.edgexfoundry.org/2.0/microservices/security/Ch-SecretStore/) and went into the `vault` container and found that there were no files in the `vault/config`folder
![CA](https://user-images.githubusercontent.com/25740210/121133473-f81f0780-c864-11eb-9296-e5924dc90d0f.png)
![vault](https://user-images.githubusercontent.com/25740210/121120486-3958ec80-c850-11eb-873f-bd67c417f9d8.png)
I want to know how to find or generate the `EdgeXFoundryCA.pem `

2. **How to find Vault Root Token.** The document says `Inspect the resp-init.json file to grab the Vault Root Token:` , But I can't find this file. Please tell me how to find the Vault Root Token file and log in to Vault or Vault Web UI.
![2021-06-08_14-51-30](https://user-images.githubusercontent.com/25740210/121137218-0707b900-c869-11eb-9028-39280825326a.png)

3. **How to configure and use API Gateway**. The document says `The configuration file can be found at https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-proxy-setup/res/configuration.toml`.
But this file does not exist . Please tell me how to configure JWT or OAuth2 for API Gateway.

Thanks!!

**Comment by lenny-intel** [comment]
@bnevis-i or @jim-wang-intel can you answer this question?

**Comment by bnevis-i** [comment]
> 1. **There is no `edgexfoundryCA.pem` in `/vault/config/pki/`**. I looked at the [document](https://docs.edgexfoundry.org/2.0/microservices/security/Ch-SecretStore/) and went into the `vault` container and found that there were no files in the `vault/config`folder

Since the vast majority of EdgeX deployments are a single node, we decided to drop the TLS feature
https://docs.edgexfoundry.org/2.0/design/adr/security/0015-in-cluster-tls/

Doc updates are in progress.


> 2. **How to find Vault Root Token.** The document says `Inspect the resp-init.json file to grab the Vault Root Token:` , But I can't find this file. Please tell me how to find the Vault Root Token file and log in to Vault or Vault Web UI.

cmd/security-secretstore-setup/res/configuation.toml
```
[SecretStore]
RevokeRootTokens = true
```

It is necessary to set this to `false` in order to prevent the root token from being revoked.

It can be done by setting an environment variable override on secretstore-setup service/container
```
SECRETSTORE_REVOKEROOTTOKENS=false
```

You can then dump it out of the resp-init.json

```console
$ docker run --rm -ti -v edgex_vault-config:/vault/config:ro alpine:latest cat /vault/config/assets/resp-init.json
(a bunch of json; look for root_token)
```

You may have to clean your environment (make clean, or docker volume prune -f) to reinitialize the secret store with leaving the root token intact.

> 3. **How to configure and use API Gateway**. The document says `The configuration file can be found at https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-proxy-setup/res/configuration.toml`.
>    But this file does not exist . Please tell me how to configure JWT or OAuth2 for API Gateway.

I just pasted that URL into my browser and it works for me.  But you'd have to rebuild the proxy-setup container with that change.

I'd try `KONGAUTH_NAME=oauth2` and see if that overrides it.  I need to verify this works so I can update the docs.

**Comment by FengZeHe** [comment]
Thank you very much and I am looking forward to the documentation update.
