### ISSUE TITLE
Explore Vault Worker Processes

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-compose#209]
Experiment with and explore performance impacts of reduced Vault memory footprint.
As was done with Kong (see #178 ) for number of threads, there are settings that may reduce the memory consumption of Vault.
This topic was brought up in the TSC meeting by @bnevis-i as suggested improvement.

Specific actions:
- Modify `compose-builder/add-security.yml` (`vault` service)
  - Add `read_only: true`  (this is just additional opportunistic container security, won't influence the experiment)
  - Remove `cap_add: - IPC_LOCK`
  - Add `SKIP_SETCAP: 1` to `environment:` section
- Modify `cmd/security-boostrapper/entrypoint-scripts/vault_wait_install.sh` and rebuild security-bootstrapper component
  - Set `disable_mlock` in Vault configuration
  - Alternatively, set `VAULT_DISABLE_MLOCK: 1` in `add-security.yml` environment variable for Vault, as above.

**Comment by jpwhitemn** [comment]
Per @bnevis-i , the recommended actions came from these sources:
https://www.vaultproject.io/docs/configuration#disable_mlock
https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh

**Comment by cloudxxx8** [comment]
We did the similar research before, but we can't find a practical way to reduce the Vault memory consumption.
`disable_mlock` can only allow Vault to use Swap file instead of memory.
Also, it might impact some security concern.
Copied from the official document:
> Disabling mlock is not recommended unless the systems running Vault only use encrypted swap or do not use swap at all. Vault only supports memory locking on UNIX-like systems that support the mlock() syscall (Linux, FreeBSD, etc). Non UNIX-like systems (e.g. Windows, NaCL, Android) lack the primitives to keep a process's entire memory address space from spilling to disk and is therefore automatically disabled on unsupported platforms.

**Comment by bnevis-i** [comment]
What @cloudxxx8 says is true.  Moreover, the  [production hardening guidelines](https://learn.hashicorp.com/tutorials/vault/production-hardening) recommend a dedicated physical machine for Vault.

In exchange for turning off MLOCK we get to make the container filesystem read-only and get to enable the no-new-privileges security flag, and possibly get EdgeX to run on hardware that it doesn't run on in secure mode today due to memory pressure.

Probably the best thing that can be done security-wise is to do some refactoring to security-secretstore-setup to enable users to "bring your own" Vault instance, that could, for example, be hosted in a cloud.

I still think we should run the experiment to see if it make a difference, and save the hand-wringing until we find out whether or not it makes a meaningful difference.

**Comment by bnevis-i** [comment]
Note:

Should test with a constrained memory environment, for example, by adding `mem=1G` to the Linux kernel command line.

https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html

**Comment by cloudxxx8** [comment]
One of our customers tried on a memory constrained hardware (On Coral TPU Dev board with 1GB RAM), and vault causes the out-of-memory error (Vault exits with error 137) even if we set disable_mlock.

**Comment by jpwhitemn** [comment]
Closed per Cloud's research and lack of results in helping with memory.
