### ISSUE TITLE
Support for EdgeX holding services via a fork in the edgexfoundry-holding organization

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/edgex-compose#233]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
edgex-compose

### Description [**REQUIRED**]
EdgeX Compose project currently only supports fully onboarded services (those within the edgexfoundry ORG). It would be nice to have a shared place where edgex-holding repos could be integrated as well. This would make it easier for the developers and testers of those projects to run EdgeX along with their additional services.

### Describe the solution you'd like
- Fork this repo into the `edgexfoundry-holding` ORG.
- Create a branch for each holding service so they can start integrating with edgex-compose
- Once the service is out of holding, small changes to that branch can be made and then PR submitted against the main repo.

### Describe alternatives you've considered

- [Explain to the end-user how to do it themselves](https://github.com/edgexfoundry-holding/device-onvif-camera/tree/main/doc/docker-compose)
- Fork `edgex-compose` into a personal repo and host the code there.

**Comment by cloudxxx8** [comment]
move this issue to the DevOps WG
@ernestojeda @ajcasagrande  since we don't build the image from holding repositories, do you have any idea to achieve this issue?

**Comment by ernestojeda** [comment]
I will defer to @lenny-intel and @jpwhitemn on this one. While this could be done, do you see value in this? I think we discussed this in the past and mentioned any holding code could be built and tested locally. Do we see a need for the greater community to have early access to these images?

In terms of scope, I don't think this issue was discussed in our Napa planning session so from a DevOps perspective, we would have to put this on hold until the next release as our scope for Napa has already been committed.
