### ISSUE TITLE
Why using environment variable name with hyphen(-) symbole?

### ISSUE THREAD

**Issue by yangsongx** [edgexfoundry/edgex-compose#61]
I found there are quite many environment vairable such as CLIENTS_EDGEX-CORE-COMMAND_HOST, 
CLIENTS_EDGEX-CORE-DATA_HOST, which contain the hypen(-) symbol.

As we know, hyphen(-) symbol is invalid for an environment variable name, especially for bash shell.

Why using such strange naming convention? It would be unfriendly when we are trying the edgex service on native Linux running system.

**Comment by cloudxxx8** [comment]
@yangsongx Actually, it is meaningful.
This environment variable is to override the configuration property.  The underscore("_") is the separator of the configuration structure.  For example, in the configuration file:
https://github.com/edgexfoundry/device-modbus-go/blob/7442c446029449b320f0bdc33bd24bf2850fc7a2/cmd/res/configuration.toml#L26
```
[Clients]
  [Clients.edgex-core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080
```

The environment variable is to override the configuration field `Clients` > `edgex-core-data` > `Host`
That's why it looks strange.

**Comment by cloudxxx8** [comment]
however, we still need to resolve the issue of "hyphen(-) symbol is invalid for an environment variable name"

**Comment by lenny-intel** [comment]
@cloudxxx8 , we may be able to address this in the env override code in go-mod-bootstrap. We already convert `.` to `_` in the setting name before comparing against the env names. So we may be able to add converting `-` to `_` so the env name will match the setting names. We'll keep this issue here to update the compose files once that change is made.

**Comment by yangsongx** [comment]
Thank you for your explaination here, now I understood the background story of this.

Thanks

**Comment by jpwhitemn** [comment]
Per Core WG meeting of 4/15/21: agree with this issue request.  We plan to move to all underscore per env var naming standards.  Hyphens get converted to underscore in code.

**Comment by lenny-intel** [comment]
Created related issue here: https://github.com/edgexfoundry/go-mod-bootstrap/issues/210

We keep this issue for the changes to the override names in the compose files once the referenced issue has been addressed

**Comment by lenny-intel** [comment]
This issues is being addressed by this PR https://github.com/edgexfoundry/go-mod-bootstrap/pull/216
Once it is merged and propagated to all the service the overrides in the compose files need to be update
