### ISSUE TITLE
What's the username-password in the database edgex-redis?

### ISSUE THREAD

**Issue by Castle1984** [edgexfoundry/edgex-compose#82]
I use `make run` to run the image in the docker-compose.yml, and I don't how to see the data in the edgex-redis.
I have tried the "root:root" to log in but it didn't work.
Here is the message:
`root@ubuntu:/edgex-compose# redis-cli`
`127.0.0.1:6379> auth "root" "root"`
`(error) WRONGPASS invalid username-password pair or user is disabled.`
Or maybe is there any other way to see the data in database?
Thanks in advance.

**Comment by lenny-intel** [comment]
The Redis password is a random auto-generated password when running the secure compose file. 
What you are trying is not possible when running in secure mode, but you can use the service REST APIs to query what is in the DB.
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.1
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.1

Otherwise you need to run the non-secure compose file: `docker-compose-no-secty.yml`

**Comment by Castle1984** [comment]
> The Redis password is a random auto-generated password when running the secure compose file.
> What you are trying is not possible when running in secure mode, but you can use the service REST APIs to query what is in the DB.
> https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.1
> https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.1
> 
> Otherwise you need to run the non-secure compose file: `docker-compose-no-secty.yml`
Oops, I get it! Thx!
